// Greek UI labels — keep brand names in English
export const L = {
  // Nav
  dashboard:   'Πίνακας',
  orders:      'Παραγγελίες',
  products:    'Προϊόντα',
  customers:   'Πελάτες',
  suppliers:   'Προμηθευτές',
  production:  'Παραγωγή',
  marketing:   'Μάρκετινγκ',
  settings:    'Ρυθμίσεις',
  signOut:     'Αποσύνδεση',
  overview:    'Επισκόπηση',
  catalog:     'Κατάλογος',
  operations:  'Λειτουργίες',
  exhibitionMode: 'Λειτουργία Έκθεσης',

  // Orders
  newOrder:          'Νέα Παραγγελία',
  orderNumber:       'Αρ. Παραγγελίας',
  orderDate:         'Ημερομηνία',
  orderTotal:        'Σύνολο',
  deposit:           'Προκαταβολή (50%)',
  remainingAmount:   'Υπόλοιπο',
  sendConfirmation:  'Αποστολή Επιβεβαίωσης',
  markDeposit:       'Κατάθεση Ελήφθη',
  exportPDF:         'Εξαγωγή PDF',
  lineItems:         'Γραμμές Παραγγελίας',
  productCode:       'Κωδικός',
  description:       'Περιγραφή',
  quantity:          'Ποσότητα',
  unitPrice:         'Τιμή Μονάδος',
  lineTotal:         'Σύνολο Γραμμής',
  notes:             'Σημειώσεις',
  addProduct:        'Προσθήκη Προϊόντος',
  saveOrder:         'Αποθήκευση Παραγγελίας',
  noItems:           'Δεν υπάρχουν γραμμές',

  // Status labels
  pendingDeposit:   'Αναμονή Προκ.',
  depositReceived:  'Προκ. Ελήφθη',
  paid:             'Εξοφλήθη',
  cancelled:        'Ακυρώθηκε',
  toPrepare:        'Προς Ετοιμασία',
  inProgress:       'Σε Εξέλιξη',
  qualityCheck:     'Ποιοτικός Έλεγχος',
  readyPackaging:   'Έτοιμο Συσκευασία',
  readyShip:        'Έτοιμο Αποστολή',
  completed:        'Ολοκληρώθηκε',
  pendingShipping:  'Σε Αναμονή',
  shipped:          'Απεστάλη',
  delivered:        'Παραδόθηκε',

  // Customer / CRM
  businessName:  'Επωνυμία',
  contactName:   'Υπεύθυνος',
  phone:         'Τηλέφωνο',
  email:         'Email',
  afm:           'ΑΦΜ',
  address:       'Διεύθυνση',
  tags:          'Ετικέτες',
  notes_:        'Παρατηρήσεις',
  orderHistory:  'Ιστορικό Παραγγελιών',
  sendEmail:     'Αποστολή Email',
  newCustomer:   'Νέος Πελάτης',
  editCustomer:  'Επεξεργασία',
  totalOrders:   'Παραγγελίες',
  totalSpent:    'Συνολικές Αγορές',

  // Products
  productName:       'Όνομα Προϊόντος',
  sku:               'Κωδικός SKU',
  costPrice:         'Τιμή Κόστους',
  salePrice:         'Τιμή Πώλησης',
  multiplier:        'Πολλαπλασιαστής',
  category:          'Κατηγορία',
  importCSV:         'Εισαγωγή CSV',
  addProduct_:       'Νέο Προϊόν',
  searchProducts:    'Αναζήτηση προϊόντων…',

  // Settings
  companyProfile:    'Στοιχεία Εταιρείας',
  companyName:       'Επωνυμία Εταιρείας',
  companyAfm:        'ΑΦΜ',
  companyDoy:        'ΔΟΥ',
  companyAddress:    'Έδρα',
  companyPhone:      'Τηλέφωνο',
  companyEmail:      'Email Εταιρείας',
  bankDetails:       'Τραπεζικά Στοιχεία',
  bankName:          'Τράπεζα',
  iban:              'IBAN',
  swift:             'BIC/SWIFT',
  invoiceSettings:   'Ρυθμίσεις Τιμολογίου',
  invoicePrefix:     'Πρόθεμα Αρ.',
  depositRate:       'Ποσοστό Προκαταβολής (%)',
  senderEmail:       'Email Αποστολής',
  senderName:        'Όνομα Αποστολέα',
  save:              'Αποθήκευση',
  saved:             'Αποθηκεύτηκε!',

  // Production
  productionSummary: 'Σύνοψη Παραγωγής',
  aggregatedQty:     'Αθροιστικές Ποσότητες',

  // PDA
  searchOrScan:  'Αναζήτηση ή σάρωση…',
  scanBarcode:   'Σάρωση Barcode',
  selectCustomer:'Επιλογή Πελάτη',
  searchCustomer:'Αναζήτηση πελάτη…',
  cart:          'Καλάθι',
  emptyCart:     'Άδειο καλάθι',
  submit:        'Υποβολή Παραγγελίας',
  orderSuccess:  'Η παραγγελία υποβλήθηκε!',
  newSale:       'Νέα Πώληση',

  // Shared
  cancel:   'Ακύρωση',
  delete:   'Διαγραφή',
  edit:     'Επεξεργασία',
  search:   'Αναζήτηση',
  export:   'Εξαγωγή',
  loading:  'Φόρτωση…',
  noData:   'Δεν βρέθηκαν αποτελέσματα',
  back:     'Πίσω',
  close:    'Κλείσιμο',
}
